### ISSUE TITLE
Its not working at all

### ISSUE THREAD

**Issue by dzulhelmi** [ashfame/facebook-like-thumbnail#10]
Installed, set the default thumbnail. 
Then i test at post that does not have any featured image or photo in it, when i paste the post link at FB, it does not showing the default thumbnail.

**Comment by ashfame** [comment]
Already replied on WP.org support forums - https://wordpress.org/support/topic/not-working-at-all-74?replies=3

Github is for developers, when talking about a specific issue, and not for general support requests. So, please continue to use forums for support.
