### ISSUE TITLE
FB thumbnail still not showing after several days

### ISSUE THREAD

**Issue by PhoenixMDI** [ashfame/facebook-like-thumbnail#12]
Hi, I'm hoping you can help.  I installed this plugin a week ago as soon as it was updated to my version of WP.  I added an image in the settings, but still the thumbnail on FB appears blank when my homepage link is posted.  My website is http://mydailyinspiration.me/ and the image currently in my settings is this one.  Thanks :)
![fb thumbnail](https://cloud.githubusercontent.com/assets/12218965/7444598/98126cf2-f182-11e4-8668-8cfdc9108e30.png)

**Comment by ashfame** [comment]
If you check your URL here, it will show you that its picking up the specified image only - https://developers.facebook.com/tools/debug/og/object/

But its so small in size, that its not used.

> og:image was not defined, could not be downloaded or was not big enough. Please define a chosen image using the og:image metatag, and use an image that's at least 200x200px and is accessible from Facebook. Image 'http://mydailyinspiration.me/wp-content/uploads/2015/04/rock-and-vine-1100x825.jpg' will be used instead.

**Comment by PhoenixMDI** [comment]
Doh!  Thank you so much!  I thought a smaller picture would be easier to handle.  I have now switched to a larger picture and it appears to be working fine!!  Thank you :)

**Comment by ashfame** [comment]
I will appreciate if you can leave a 5 star rating on WP.org - https://wordpress.org/plugins/facebook-like-thumbnail/ :)

**Comment by PhoenixMDI** [comment]
Done!  Thanks again :)
