### ISSUE TITLE
Facebook plugin not working

### ISSUE THREAD

**Issue by crometool** [ashfame/facebook-like-thumbnail#16]
I installed the plugin and it is still pulling the default images from facebook. I have set the image I would like for it to pull but no go. Here is the site.

 http://www.red-skin-syndrome.com/

Here is a screen shot:

![image](https://cloud.githubusercontent.com/assets/14784267/10021536/4afa12fe-60fd-11e5-85d8-5546a91d8069.png)

Here is a screen shot of the plugin 

![image](https://cloud.githubusercontent.com/assets/14784267/10021583/89b4e140-60fd-11e5-800a-9960fcac6429.png)

**Comment by ashfame** [comment]
You will need to clear your page cache, if you are using a plugin like W3 total cache or WP super cache plugin.

Also, Github isn't the place for support, please use right channels i.e. WP.org support forums
