### ISSUE TITLE
pic selection still doesn't work

### ISSUE THREAD

**Issue by GlobalSwimSeries** [ashfame/facebook-like-thumbnail#17]
Hi Ashfame,

I downloaded and installed your "Facebook Like Thumbnail" plugin... but I'm still getting the wrong pic.  I'm a bit of a newbie and must be doing something wrong, but not sure what?  I cleared the Chrome cache, but that didn't work...

Cheers,

Rob

**Comment by ashfame** [comment]
Hi,

Facebook will update it for all the pages within 24hrs. If you want to refresh for a particular page manually, then you can use the debug tool - https://developers.facebook.com/tools/debug/
