### ISSUE TITLE
No Featured Image box on Product Pages in Woocommerce

### ISSUE THREAD

**Issue by Mqrius** [ashfame/facebook-like-thumbnail#19]
Woocommerce has Product Pages, which behave fairly similarly to normal Pages. I'd love to be able to set the Featured Image for those as well.

**Comment by ashfame** [comment]
Sorry was on vacations! It should be showing up the first image it finds in media attachments for that product page.

Also, the plugin is easily extendible if you want to just make it work as per your logic. Pull requests are welcome too!
