### ISSUE TITLE
Hi, issue with photos

### ISSUE THREAD

**Issue by tkrypas** [ashfame/facebook-like-thumbnail#20]
Hi ,

there is an issue with photos of posts!
Even if all posts have photos, when sharing all stack at one specific photo.

http://www.epaggelmagynaika.gr/psyxografimata/%CF%88%CF%85%CF%87%CE%BF%CE%B3%CF%81%CE%B1%CF%86%CE%B7%CE%BC%CE%B1%CF%84%CE%B1/%CE%BC%CE%B5-%CF%87%CE%B9%CE%BF%CF%8D%CE%BC%CE%BF%CF%81-%CE%BA%CE%B1%CE%B9-%CE%B1%CE%BB%CE%AC%CF%84%CE%B9/

Regards,

Thomas

**Comment by ashfame** [comment]
Hi, Couldn't load that page. 502 error.

Can you provide an example where what should show up and what's showing up?
