### ISSUE TITLE
Incorrect Thumbmail being used

### ISSUE THREAD

**Issue by urbanmov** [ashfame/facebook-like-thumbnail#21]
This plugin was previously working fine, but now when used the incorrect thumbnail is being selected.

Can you assist please.

**Comment by ashfame** [comment]
Can you provide an example where what should show up and what's showing up?

**Comment by urbanmov** [comment]
*     ADELAIDE | BRISBANE | MELBOURNE | LONDON*











Hi Ashframe,

The problem has been resloved. I had to change the size of picture I chose
as the thumbmail


​
 Kind Regards

* Sean Conrad  *
*   (DJSoulchild*)
*     Director*
*(Brisbane Office)*

*28 Park Edge Drive |Springfield Lakes | **QLD 4300*
*Office: +61(0) 435 327 233*
Facebook <http://www.facebook.com/akaDjSoulchild> | Twitter
<https://twitter.com/akasoulchild> | Instagram
<http://instagram.com/aka_soulchild/>* |* *YouTube
<https://www.youtube.com/user/akaDjSoulchild>*

*Click Here to Listen to Urban Movement Radio Station
<http://streema.com/radios/play/103557>*



*Bringing Urban Music to Australasia*

This email is intended for the addressee only and may contain privileged or
confidential information. If received in error, please notify the
originator immediately. Any unauthorised use, disclosure, copying or
alteration of this email is strictly forbidden. Views or opinions expressed
in this email do not necessarily represent those of Urban Movement
Entertainments. All Urban Movement Entertainments email activity is
monitored for virus, racist, obscene, or otherwise inappropriate activity.
No responsibility is accepted by Urban Movement Entertainments for any loss
or damage arising in any way from the receipt or use of this email.
