### ISSUE TITLE
Does not show the image highlights of the link in facebook

### ISSUE THREAD

**Issue by angear** [ashfame/facebook-like-thumbnail#22]
Does not show the image highlights of the link in facebook, although the image is greater than 200 px not logor make muetsre the outstanding image of a note with lin on facebook, only shows the logo of my web page, how do I solve this?

**Comment by ashfame** [comment]
@angear Please specify the URL so that I can check. Also did you try the debug tool https://developers.facebook.com/tools/debug/ ?

**Comment by angear** [comment]
If you tried with https://developers.facebook.com/tools/debug/ but too many links to do it that way and I program notes very often by the nature of the Web, the URL of the site is http: // www. Lapiragua.co/
