### ISSUE TITLE
THUMBNAIL PROBLEM WITH MOBILE

### ISSUE THREAD

**Issue by andreabo86** [ashfame/facebook-like-thumbnail#23]
When we share a link from our wordpress website : (www.irpiniapost.it) it often the image on facebook is very small than normal. Sometimes it works correctly. We use always the same dimension 1200x630 or similar
![foto big](https://user-images.githubusercontent.com/60194415/72922520-77359d80-3d4d-11ea-9805-0f70bb563a0a.jpg)
![foto small](https://user-images.githubusercontent.com/60194415/72922521-77359d80-3d4d-11ea-9653-de1dd3a3419a.jpg)

**Comment by ashfame** [comment]
@andreabo86 Sorry, just saw this now. I checked and your site has other plugins trying to specify the image to use when sharing links on social media, which is causing some or the other image to show up. You need to let one of them handle everything.
