### ISSUE TITLE
Image for Facebook like 

### ISSUE THREAD

**Issue by JBlaaz** [ashfame/facebook-like-thumbnail#8]
I am a technically-challenged designer, and I'm sure this is a dumb question, but here goes: I installed the WP plugin for one of my sites, THINKING that it should allow me to link to an image in my library that will be the "gravatar" that's associated with the site when shared  on Facebook, or wherever . But I'm not sure if that the case. Is the box below supposed to link to the Facebook logo "like" ICON, or to the blog IMAGE we want to show when we link the blog site to Facebook? I don't understand what is being asked for in the link box. Thanks for any help!
![fblikeurl](https://cloud.githubusercontent.com/assets/10632903/5838402/391528b6-a155-11e4-80f3-dcc52d265c71.png)

**Comment by ashfame** [comment]
Yes, that's right. You are supposed to enter a image URL.

Eventually I will move on to just picking up an image from media library or upload a new one right from the page.

**Comment by JBlaaz** [comment]
Thanks so much for your reply!!  So I should find an image in my WP media library, click for "attachment details" and use the url that's listed for that particular image, correct?  Sorry to be so dense, but I finally got most of the plugins working correctly and don't want to break anything!

Best,

Jean


On Jan 21, 2015, at 4:22 PM, Ashfame wrote:

> Yes, that's right. You are supposed to enter a image URL.
> 
> Eventually I will move on to just picking up an image from media library or upload a new one right from the page.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Jean Wood Blasingame
ph. 336.207.1872

**Comment by ashfame** [comment]
That's right! A url which when opened up in browser and shows you an image, is good to go.

**Comment by JBlaaz** [comment]
Thanks so much!!

Jean


On Jan 22, 2015, at 12:22 PM, Ashfame wrote:

> That's right! A url which when opened up in browser and shows you an image, is good to go.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Jean Wood Blasingame
ph. 336.207.1872

**Comment by ashfame** [comment]
@JBlaaz New v0.4 has a media uploader attached :)
